name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Comamnd
        run: echo "Hi There!"
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Comamnd
        run: echo "Good bye"