name: Deploying a web site
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Printing a message
        run: echo "Hi there!"
  test1:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Printing another message
        run: echo "Good bye!"
